### ISSUE TITLE
Tracking the big tidy up

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#14]
The building database has grown out of a proof of concept and so requires a lot of tidying up in areas. Here is a list of just some of what needs to be looked at:

- [ ] Library duplication (eg. using both jQuery and Zepto)
- [ ] Moving from external libraries to locally-hosted libraries (or not)
- [ ] Clean up the SASS stylesheet
- [ ] Lots more...

**Comment by robhawkes** [comment]
Closing as a lot of this has already happened or will do via #33
